#!/bin/sh
erl -pa `dirname $0`/../ebin -pa `dirname $0`/ebin -run udg_tests_1 t -noshell -noinput -run erlang halt
erl -pa `dirname $0`/../ebin -pa `dirname $0`/ebin -run udg_tests_2 t -noshell -noinput -run erlang halt
